openapi: 3.0.3
info:
  title: My application Swagger
  description: This is an example swagger for the application made for the Galicia challenge
  termsOfService: http://swagger.io/terms/
  contact:
    email: margus@gmail.com
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  version: 1.0.11
externalDocs:
  description: Find out more about Swagger
  url: http://swagger.io
servers:
  - url: https://myserver.com
paths:
  /healthcheck:
    get:
      tags:
        - Application
      description: Checks if the application is healthy
      responses:
        '200':
          description: successful operation
          content:
            application/json:
              schema:
                type: object
                properties:
                  message:
                    type: string
                    example: healthy
        '500':
          description: successful operation
          content:
            application/json:
              schema:
                type: string
                example: Internal server error